intro-world: beacon_intro
survival-world: world
intro-location:
  x: 0.5
  y: 100.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0
teleport-delay-seconds: 5
wild:
  min-radius: 1500
  max-radius: 5000
combat-tag-seconds: 10
contact-line: 'Contact Danzi on Discord if you have questions, or use /behelp or /tutorial for information.'
rankup:
  costs: [25000, 100000, 350000, 1000000, 3500000]
  prestige-multipliers: [1.0, 2.0, 3.5, 5.0]
prestige-costs: [10000000, 25000000, 50000000]
relics:
  aura-radius: 20
  aura-cooldown-minutes: 20
  nullshard-radius: 50
