name: Build Fabric Mod

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Set up Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'

      - name: Show files
        run: ls -la && find src -maxdepth 5 -type f | sort

      - name: Build
        run: gradle build

      - name: Upload mod jar
        uses: actions/upload-artifact@v4
        with:
          name: beacon-economy-v1-jar
          path: build/libs/*.jar
